### ISSUE TITLE
用作控制器的切换的时候

### ISSUE THREAD

**Issue by Easyzhan** [757094197/TestShopingCart#1]
效果不是那么顺畅，会闪一下你知道是什么原因吗

**Comment by fish-yan** [comment]
我这测试并没有你说的闪一下的情况啊,很流畅的

**Comment by fish-yan** [comment]
我知道你的原因了,在导航条存在的情况下, 会闪一下, 但这只是在虚拟机上才会出现,真机是上没有一点问题的.
